# Generated by Django 5.2.3 on 2025-06-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('salario', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('encontrado_em', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
